### ISSUE TITLE
More detailed exceptions.

### ISSUE THREAD

**Issue by rdohms** [schmittjoh/serializer#738]
I'll​ put in the work and PR for this, but want to check with authors if this fits their vision.

Currently if an error occurs in serializing or deserializing the same Runtime exception is thrown.

I would like to create two new exceptions, a SerializeException and the equivalent for deserialization. As I see it they would do nothing more then extend the runtime exception but providing the information of which operation is underway.

My use case is I would like to create a exception listener that catches all deserialization exceptions and wraps them in a 400 error, currently doing so is clunky as the runtime exception can happen in both operations and I would be getting g false positives.

Is this acceptable? If so I'll get to work on the PR.

Cheers.

**Comment by goetas** [comment]
Sounds good to me

**Comment by goetas** [comment]
done in https://github.com/schmittjoh/serializer/pull/743/commits/09ff77ee1fe6b256ee6f05c6c69f5dbff7b9df7e

**Comment by rdohms** [comment]
@goetas please correct me if I'm wrong.

It appears the fix you have creates local versions of the Exception, which I believe is not solving the real problem here. Even if with this change we can now limit to Exceptions from JMS, we are still not able to differentiate between exceptions in the Serialize or Deserialize processes, as I described above.

I would like to keep this issue open, and would love to contribute if I can get a green flag.

**Comment by goetas** [comment]
does it make sense to duplicate all the exceptions? (imo not...)

Suggestions?

**Comment by goetas** [comment]
can you explain a real world use case?

**Comment by rdohms** [comment]
@goetas personally duplicating them did not make too much of a change, and the use of SPL exceptions is fine by me. But we can achieve the Serialize/Deserialize goal without making this change as well.

**Comment by rdohms** [comment]
@goetas sure.

We have a middleware that does deserialization on the fly, and one that does serialization as well, so the process is all automated. In our error handling middleware, I would like to convert `deserialization` errors into 400's and serialization into something else. 

Right now, unless i catch the exceptions at the source I cannot differentiate. So in general having more clear exceptions that reflect where you are in the process would be welcome.
